os:
  - linux

language: cpp
sudo: required
dist: xenial

compiler: 
  - gcc
  - clang

script:
  - mkdir build
  - pushd build
  - cmake ..
  - popd
  - cmake --build build

install:
  source ./travis/install.sh
