name: Sourcehold

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        target-platform: ["host"]
        include:
          - os: ubuntu-latest
            install-dependencies: "sh ./ubuntu/install-dependencies.sh"
            cmake-configure-options: ""
            cmake-build-options: ""
            uploaded-artifact-name: "sourcehold-linux-amd64"
          - os: macos-latest
            install-dependencies: "sh ./apple/install-dependencies-macos.sh"
            cmake-configure-options: ""
            cmake-build-options: ""
            uploaded-artifact-name: "sourcehold-mac-os"
          # Use different target platform here just to force new job spawning
          - target-platform: "ios-simulator"
            os: macos-latest
            install-dependencies: "sh ./apple/install-dependencies-ios.sh -s -d 11.0 ./thirdparty/ios"
            cmake-configure-options: '-GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCMAKE_OSX_ARCHITECTURES="x86_64"'
            cmake-build-options: "-- -sdk iphonesimulator"
            uploaded-artifact-name: "sourcehold-ios"
    
    name: ${{ matrix.os }} - ${{ matrix.target-platform }}
    
    steps:
    - name: Set up environment variables
      # Unfortunately workflow level env variables can not be accessed at job level
      # (see https://github.community/t/how-to-set-and-access-a-workflow-variable/17335)
      # in our case this is BUILD_TYPE. Thus we have to define it here in such weird way.
      run: |
          if [[ ${{ matrix.target-platform }} == 'ios-simulator' ]]; then
            echo "BUILD_ARTIFACT_PARENT_DIR_PATH=${{ github.workspace }}/build/${{ env.BUILD_TYPE }}-iphonesimulator" >> $GITHUB_ENV
            echo "BUILD_ARTIFACT_NAME=Stronghold.app" >> $GITHUB_ENV
          else
            echo "BUILD_ARTIFACT_PARENT_DIR_PATH=${{ github.workspace }}/build" >> $GITHUB_ENV
            echo "BUILD_ARTIFACT_NAME=Stronghold" >> $GITHUB_ENV
          fi
    
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        submodules: 'true'
      
    - name: Cache dependencies
      if: ${{ matrix.target-platform == 'ios-simulator' }}
      uses: actions/cache@v2
      env:
        cache-name: cache-${{ matrix.target-platform }}-dependencies
      with:
        path: ${{ github.workspace }}/thirdparty/ios
        key: ${{ env.cache-name }}
      
    - name: Install dependencies
      env:
        INSTALL_DEPENDENCIES: ${{ matrix.install-dependencies }}
      # Install all the required dependencies to build Sourcehold
      run: $INSTALL_DEPENDENCIES

    - name: Create build environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      env:
        CMAKE_CONFIGURE_OPTIONS: ${{ matrix.cmake-configure-options }}
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE $CMAKE_CONFIGURE_OPTIONS

    - name: Build
      working-directory: ${{ github.workspace }}/build
      shell: bash
      env:
        CMAKE_BUILD_OPTIONS: ${{ matrix.cmake-build-options }}
      # Execute the build. You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE $CMAKE_BUILD_OPTIONS

    - name: Make artifacts
      shell: bash
      run: |
        cd "$BUILD_ARTIFACT_PARENT_DIR_PATH"
        zip -r ${{ github.workspace }}/${{ matrix.uploaded-artifact-name }}.zip "$BUILD_ARTIFACT_NAME"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.uploaded-artifact-name }}
        path: ${{ github.workspace }}/${{ matrix.uploaded-artifact-name }}.zip
